#include "Engine/Renderer/glbindings.h"

PFNGLCLEARPROC						glClear						= nullptr;
PFNGLCLEARCOLORPROC					glClearColor				= nullptr;
PFNWGLGETEXTENSIONSSTRINGARBPROC	wglGetExtensionsStringARB	= nullptr;
PFNWGLCHOOSEPIXELFORMATARBPROC		wglChoosePixelFormatARB		= nullptr;
PFNWGLCREATECONTEXTATTRIBSARBPROC	wglCreateContextAttribsARB	= nullptr;
PFNGLENABLEPROC						glEnable					= nullptr;
PFNGLBLENDFUNCPROC					glBlendFunc					= nullptr;
PFNGLLINEWIDTHPROC					glLineWidth					= nullptr;
PFNGLSHADERSOURCEPROC				glShaderSource				= nullptr;
PFNGLCOMPILESHADERPROC				glCompileShader				= nullptr;
PFNGLCREATESHADERPROC				glCreateShader				= nullptr;
PFNGLGETSHADERIVPROC				glGetShaderiv				= nullptr;
PFNGLDELETESHADERPROC				glDeleteShader				= nullptr;
PFNGLGETSHADERINFOLOGPROC			glGetShaderInfoLog			= nullptr;
PFNGLCREATEPROGRAMPROC				glCreateProgram				= nullptr;
PFNGLATTACHSHADERPROC				glAttachShader				= nullptr;
PFNGLLINKPROGRAMPROC				glLinkProgram				= nullptr;
PFNGLGETPROGRAMIVARBPROC			glGetProgramiv				= nullptr;
PFNGLDELETEPROGRAMPROC				glDeleteProgram				= nullptr;
PFNGLDETACHSHADERPROC				glDetachShader				= nullptr;
PFNGLGETPROGRAMINFOLOGPROC			glGetProgramInfoLog			= nullptr;
PFNGLGENBUFFERSPROC					glGenBuffers				= nullptr;
PFNGLBINDBUFFERPROC					glBindBuffer				= nullptr;
PFNGLBUFFERDATAPROC					glBufferData				= nullptr;
PFNGLDELETEBUFFERSPROC				glDeleteBuffers				= nullptr;
PFNGLGENVERTEXARRAYSPROC			glGenVertexArrays			= nullptr;
PFNGLBINDVERTEXARRAYPROC			glBindVertexArray			= nullptr;
PFNGLGETATTRIBLOCATIONPROC			glGetAttribLocation			= nullptr;		
PFNGLENABLEVERTEXATTRIBARRAYPROC	glEnableVertexAttribArray	= nullptr;
PFNGLVERTEXATTRIBPOINTERPROC		glVertexAttribPointer		= nullptr;
PFNGLUSEPROGRAMPROC					glUseProgram				= nullptr;
PFNGLDRAWARRAYSPROC					glDrawArrays				= nullptr;
PFNGLBINDTEXTUREPROC				glBindTexture				= nullptr;
PFNGLDISABLEPROC					glDisable					= nullptr;
PFNGLGETUNIFORMLOCATIONPROC			glGetUniformLocation		= nullptr;
PFNGLPROGRAMUNIFORM4FVPROC			glProgramUniform4fv			= nullptr;
PFNGLPROGRAMUNIFORMMATRIX4FVPROC	glProgramUniformMatrix4fv	= nullptr;
PFNGLSAMPLERPARAMETERIPROC			glSamplerParameteri			= nullptr;
PFNGLGENSAMPLERSPROC				glGenSamplers				= nullptr;
PFNGLDELETESAMPLERSPROC				glDeleteSamplers			= nullptr;
PFNGLPIXELSTOREIPROC				glPixelStorei				= nullptr; 
PFNGLGENTEXTURESPROC				glGenTextures				= nullptr; 
PFNGLTEXPARAMETERIPROC				glTexParameteri				= nullptr;
PFNGLTEXIMAGE2DPROC					glTexImage2D				= nullptr;
PFNGLGETERRORPROC					glGetError					= nullptr;
PFNGLBINDSAMPLERPROC				glBindSampler				= nullptr;
PFNGLACTIVETEXTUREPROC				glActiveTexture				= nullptr;
PFNGLUNIFORM1IPROC					glUniform1i					= nullptr;
PFNGLPOLYGONMODEPROC				glPolygonMode				= nullptr;
PFNGLGENFRAMEBUFFERSPROC			glGenFramebuffers			= nullptr;
PFNGLDELETEFRAMEBUFFERSPROC			glDeleteFramebuffers		= nullptr;
PFNGLBINDFRAMEBUFFERPROC			glBindFramebuffer			= nullptr;
PFNGLFRAMEBUFFERTEXTUREPROC			glFramebufferTexture		= nullptr;
PFNGLDRAWBUFFERSPROC				glDrawBuffers				= nullptr;
PFNGLCHECKFRAMEBUFFERSTATUSPROC     glCheckFramebufferStatus	= nullptr;
PFNGLBLITFRAMEBUFFERPROC			glBlitFramebuffer			= nullptr;
PFNGLDEPTHFUNCPROC					glDepthFunc					= nullptr;
PFNGLDEPTHMASKPROC					glDepthMask					= nullptr;
PFNGLCLEARDEPTHFPROC				glClearDepthf				= nullptr;
PFNGLDRAWELEMENTSPROC				glDrawElements				= nullptr;
PFNGLCULLFACEPROC					glCullFace					= nullptr;
PFNGLFRONTFACEPROC					glFrontFace					= nullptr;
PFNGLUNIFORM4FPROC					glUniform4f					= nullptr;
PFNGLBLENDEQUATIONPROC				glBlendEquation				= nullptr;
PFNGLUNIFORM1FPROC					glUniform1f					= nullptr;
PFNGLBLENDFUNCSEPARATEPROC			glBlendFuncSeparate			= nullptr;
PFNGLUNIFORM3FPROC					glUniform3f					= nullptr;
PFNGLUNIFORM4FVPROC					glUniform4fv				= nullptr;
PFNGLUNIFORM3FVPROC					glUniform3fv				= nullptr;
PFNGLUNIFORM1FVPROC					glUniform1fv				= nullptr;
PFNGLTEXSTORAGE2DPROC				glTexStorage2D				= nullptr;
PFNGLTEXSUBIMAGE2DPROC				glTexSubImage2D				= nullptr;
PFNGLCLEARBUFFERIVPROC				glClearBufferiv				= nullptr;
PFNGLCLEARBUFFERFVPROC				glClearBufferfv				= nullptr;
PFNGLREADPIXELSPROC					glReadPixels				= nullptr;
PFNGLDELETETEXTURESPROC				glDeleteTextures			= nullptr;
PFNGLGENERATEMIPMAPPROC				glGenerateMipmap			= nullptr;
PFNGLVIEWPORTPROC					glViewport					= nullptr;


void BindGLFunctions() {
	GL_BIND_FUNCTION( glClear );
	GL_BIND_FUNCTION( glClearColor );
	GL_BIND_FUNCTION( wglGetExtensionsStringARB ); 
	GL_BIND_FUNCTION( wglChoosePixelFormatARB ); 
	GL_BIND_FUNCTION( wglCreateContextAttribsARB );
	GL_BIND_FUNCTION( glEnable );
	GL_BIND_FUNCTION( glBlendFunc );
	GL_BIND_FUNCTION( glLineWidth );
	GL_BIND_FUNCTION( glShaderSource );
	GL_BIND_FUNCTION( glCompileShader );
	GL_BIND_FUNCTION( glCreateShader );
	GL_BIND_FUNCTION( glGetShaderiv	);
	GL_BIND_FUNCTION( glDeleteShader );
	GL_BIND_FUNCTION( glGetShaderInfoLog );
	GL_BIND_FUNCTION( glCreateProgram );	
	GL_BIND_FUNCTION( glAttachShader );	
	GL_BIND_FUNCTION( glLinkProgram	);
	GL_BIND_FUNCTION( glGetProgramiv );	
	GL_BIND_FUNCTION( glDeleteProgram );	
	GL_BIND_FUNCTION( glDetachShader );	
	GL_BIND_FUNCTION( glGetProgramInfoLog );
	GL_BIND_FUNCTION( glGenBuffers );
	GL_BIND_FUNCTION( glBindBuffer );
	GL_BIND_FUNCTION( glBufferData );
	GL_BIND_FUNCTION( glDeleteBuffers );
	GL_BIND_FUNCTION( glGenVertexArrays );
	GL_BIND_FUNCTION( glBindVertexArray );
	GL_BIND_FUNCTION( glGetAttribLocation );			
	GL_BIND_FUNCTION( glEnableVertexAttribArray	);
	GL_BIND_FUNCTION( glVertexAttribPointer	);
	GL_BIND_FUNCTION( glUseProgram );			
	GL_BIND_FUNCTION( glDrawArrays );	
	GL_BIND_FUNCTION( glBindTexture );
	GL_BIND_FUNCTION( glDisable );
	GL_BIND_FUNCTION( glGetUniformLocation );
	GL_BIND_FUNCTION( glProgramUniform4fv );
	GL_BIND_FUNCTION( glProgramUniformMatrix4fv );
	GL_BIND_FUNCTION( glSamplerParameteri );
	GL_BIND_FUNCTION( glGenSamplers );
	GL_BIND_FUNCTION( glDeleteSamplers );
	GL_BIND_FUNCTION( glPixelStorei );
	GL_BIND_FUNCTION( glGenTextures );
	GL_BIND_FUNCTION( glTexParameteri );
	GL_BIND_FUNCTION( glTexImage2D );
	GL_BIND_FUNCTION( glGetError );
	GL_BIND_FUNCTION( glBindSampler );
	GL_BIND_FUNCTION( glActiveTexture );
	GL_BIND_FUNCTION( glUniform1i ); 
	GL_BIND_FUNCTION( glPolygonMode );
	GL_BIND_FUNCTION( glGenFramebuffers );
	GL_BIND_FUNCTION( glDeleteFramebuffers );
	GL_BIND_FUNCTION( glBindFramebuffer );
	GL_BIND_FUNCTION( glFramebufferTexture );
	GL_BIND_FUNCTION( glDrawBuffers );
	GL_BIND_FUNCTION( glCheckFramebufferStatus );
	GL_BIND_FUNCTION( glBlitFramebuffer );
	GL_BIND_FUNCTION( glDepthFunc );
	GL_BIND_FUNCTION( glDepthMask );
	GL_BIND_FUNCTION( glClearDepthf );
	GL_BIND_FUNCTION( glDrawElements );
	GL_BIND_FUNCTION( glCullFace );
	GL_BIND_FUNCTION( glFrontFace );
	GL_BIND_FUNCTION( glUniform4f );
	GL_BIND_FUNCTION( glBlendEquation );
	GL_BIND_FUNCTION( glUniform1f );
	GL_BIND_FUNCTION( glBlendFuncSeparate );
	GL_BIND_FUNCTION( glUniform3f );
	GL_BIND_FUNCTION( glUniform4fv );
	GL_BIND_FUNCTION( glUniform3fv );
	GL_BIND_FUNCTION( glUniform1fv );
	GL_BIND_FUNCTION( glTexStorage2D );
	GL_BIND_FUNCTION( glTexSubImage2D );
	GL_BIND_FUNCTION( glClearBufferiv );
	GL_BIND_FUNCTION( glClearBufferfv );
	GL_BIND_FUNCTION( glReadPixels );
	GL_BIND_FUNCTION( glDeleteTextures );
	GL_BIND_FUNCTION( glGenerateMipmap );
	GL_BIND_FUNCTION( glViewport );
}